(function(){'use strict';
const ANN_GAS='https://script.google.com/macros/s/AKfycbyUB8drjL1dSJedYjKIKjVc5gzIE3Pe-QS0FF8o1_zU4NkAweGLFquhHLfy1Nt_eITA-Q/exec';
const ANN_SEEN='kudajitu_announcement_seen_v1';
function annJsonp(url,timeout){return new Promise(function(resolve,reject){var cb='__ann_'+Date.now()+'_'+Math.random().toString(36).slice(2),s=document.createElement('script'),done=false,t=setTimeout(function(){finish();reject(Error('timeout'))},timeout||10000);function finish(){if(done)return;done=true;clearTimeout(t);s.remove();try{delete window[cb]}catch(e){window[cb]=undefined}}window[cb]=function(d){finish();d&&d.success!==false?resolve(d):reject(Error(d&&d.message||'server error'))};s.src=url+(url.indexOf('?')>=0?'&':'?')+'callback='+cb+'&_='+Date.now();s.onerror=function(){finish();reject(Error('network error'))};document.head.appendChild(s)})}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})}
function build(){if(document.getElementById('annOverlay'))return;var css=document.createElement('style');css.textContent='.ann-overlay{position:fixed;inset:0;z-index:9999;background:rgba(0,0,0,.76);backdrop-filter:blur(7px);display:flex;align-items:center;justify-content:center;padding:18px}.ann-card{width:min(520px,100%);background:linear-gradient(145deg,#071719,#0a181b);border:1px solid rgba(45,212,191,.3);border-radius:24px;box-shadow:0 25px 80px rgba(0,0,0,.55);overflow:hidden;animation:annIn .22s ease}.ann-head{padding:20px 22px 12px;display:flex;align-items:flex-start;gap:13px}.ann-icon{width:44px;height:44px;border-radius:14px;display:flex;align-items:center;justify-content:center;flex:0 0 44px;font-size:20px}.ann-info{background:rgba(20,184,166,.13);color:#5eead4;border-color:rgba(20,184,166,.3)}.ann-warning{background:rgba(245,158,11,.13);color:#fbbf24;border-color:rgba(245,158,11,.3)}.ann-important{background:rgba(239,68,68,.13);color:#f87171;border-color:rgba(239,68,68,.3)}.ann-title{font-size:18px;font-weight:800;line-height:1.25;color:#fff}.ann-content{padding:4px 22px 20px;color:#cbd5e1;font-size:14px;line-height:1.7;white-space:pre-wrap;word-break:break-word;max-height:52vh;overflow:auto}.ann-actions{padding:14px 22px 20px;border-top:1px solid rgba(45,212,191,.1);display:flex;justify-content:flex-end}.ann-close{border:0;border-radius:12px;padding:10px 18px;background:#0d9488;color:#fff;font-weight:800;cursor:pointer}.ann-x{margin-left:auto;border:0;background:transparent;color:#94a3b8;font-size:20px;cursor:pointer}@keyframes annIn{from{opacity:0;transform:translateY(10px) scale(.98)}to{opacity:1;transform:none}}';document.head.appendChild(css)}
function closeAnn(){var e=document.getElementById('annOverlay');if(e)e.remove()}
function showAnn(a){if(!a||!a.enabled||(!a.title&&!a.content))return;var key=String(a.updatedAt||a.title+'|'+a.content);if(a.mode!=='always'&&localStorage.getItem(ANN_SEEN)===key)return;build();var type=['info','warning','important'].indexOf(a.type)>=0?a.type:'info',icon=type==='important'?'fa-triangle-exclamation':type==='warning'?'fa-bell':'fa-circle-info';var o=document.createElement('div');o.id='annOverlay';o.className='ann-overlay';o.innerHTML='<div class="ann-card" role="dialog" aria-modal="true"><div class="ann-head"><div class="ann-icon ann-'+type+'"><i class="fa-solid '+icon+'"></i></div><div><div class="ann-title">'+esc(a.title||'INFORMASI KUDAJITU FM')+'</div><div style="font-size:10px;color:#64748b;margin-top:4px;text-transform:uppercase;letter-spacing:.12em">Pengumuman</div></div><button class="ann-x" aria-label="Tutup">×</button></div><div class="ann-content">'+esc(a.content||'')+'</div><div class="ann-actions"><button class="ann-close">✓ Saya Mengerti</button></div></div>';document.body.appendChild(o);o.querySelector('.ann-x').onclick=closeAnn;o.querySelector('.ann-close').onclick=function(){if(a.mode!=='always')localStorage.setItem(ANN_SEEN,key);closeAnn()};o.addEventListener('click',function(e){if(e.target===o)closeAnn()})}
function loadAnnouncement(){annJsonp(ANN_GAS+'?action=announcement',10000).then(function(r){showAnn(r.announcement)}).catch(function(){})}
window.KUDAJITUAnnouncement={load:loadAnnouncement};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',loadAnnouncement);else loadAnnouncement();setInterval(loadAnnouncement,60000);
})();
