(function(){'use strict';
const ANN_GAS='https://script.google.com/macros/s/AKfycbyUB8drjL1dSJedYjKIKjVc5gzIE3Pe-QS0FF8o1_zU4NkAweGLFquhHLfy1Nt_eITA-Q/exec';
const ANN_SEEN='kudajitu_announcement_seen_v1';
const AUTH_TOKEN='kudajitu_member_token_v1';
function annJsonp(url,timeout){return new Promise(function(resolve,reject){var cb='__ann_'+Date.now()+'_'+Math.random().toString(36).slice(2),s=document.createElement('script'),done=false,t=setTimeout(function(){finish();reject(Error('timeout'))},timeout||10000);function finish(){if(done)return;done=true;clearTimeout(t);s.remove();try{delete window[cb]}catch(e){window[cb]=undefined}}window[cb]=function(d){finish();d&&d.success!==false?resolve(d):reject(Error(d&&d.message||'server error'))};s.src=url+(url.indexOf('?')>=0?'&':'?')+'callback='+cb+'&_='+Date.now();s.onerror=function(){finish();reject(Error('network error'))};document.head.appendChild(s)})}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})}
function build(){if(document.getElementById('annStyles'))return;var css=document.createElement('style');css.id='annStyles';css.textContent='.ann-overlay{position:fixed;inset:0;z-index:9999;background:rgba(0,0,0,.76);backdrop-filter:blur(7px);display:flex;align-items:center;justify-content:center;padding:18px}.ann-card{width:min(520px,100%);background:linear-gradient(145deg,#071719,#0a181b);border:1px solid rgba(45,212,191,.3);border-radius:24px;box-shadow:0 25px 80px rgba(0,0,0,.55);overflow:hidden;animation:annIn .22s ease}.ann-head{padding:20px 22px 12px;display:flex;align-items:flex-start;gap:13px}.ann-icon{width:44px;height:44px;border-radius:14px;display:flex;align-items:center;justify-content:center;flex:0 0 44px;font-size:20px}.ann-info{background:rgba(20,184,166,.13);color:#5eead4;border-color:rgba(20,184,166,.3)}.ann-warning{background:rgba(245,158,11,.13);color:#fbbf24;border-color:rgba(245,158,11,.3)}.ann-important{background:rgba(239,68,68,.13);color:#f87171;border-color:rgba(239,68,68,.3)}.ann-title{font-size:18px;font-weight:800;line-height:1.25;color:#fff}.ann-content{padding:4px 22px 20px;color:#cbd5e1;font-size:14px;line-height:1.7;white-space:pre-wrap;word-break:break-word;max-height:52vh;overflow:auto}.ann-actions{padding:14px 22px 20px;border-top:1px solid rgba(45,212,191,.1);display:flex;justify-content:flex-end}.ann-close{border:0;border-radius:12px;padding:10px 18px;background:#0d9488;color:#fff;font-weight:800;cursor:pointer}.ann-x{margin-left:auto;border:0;background:transparent;color:#94a3b8;font-size:20px;cursor:pointer}@keyframes annIn{from{opacity:0;transform:translateY(10px) scale(.98)}to{opacity:1;transform:none}}.auth-overlay{position:fixed;inset:0;z-index:10000;background:rgba(2,8,10,.96);backdrop-filter:blur(10px);display:flex;align-items:center;justify-content:center;padding:18px}.auth-card{width:min(420px,100%);background:linear-gradient(145deg,#071719,#0a181b);border:1px solid rgba(45,212,191,.3);border-radius:24px;padding:28px;box-shadow:0 25px 80px rgba(0,0,0,.6)}.auth-field{width:100%;box-sizing:border-box;background:#030a0c;border:1px solid #115e59;border-radius:12px;padding:12px 14px;color:#fff;outline:0;margin-top:7px}.auth-field:focus{border-color:#2dd4bf}.auth-btn{width:100%;border:0;border-radius:12px;padding:12px;background:#0d9488;color:#fff;font-weight:800;cursor:pointer;margin-top:14px}.auth-btn:disabled{opacity:.55;cursor:wait}.auth-msg{min-height:18px;font-size:12px;margin-top:10px;color:#f87171}.member-chip{display:inline-flex;align-items:center;gap:7px;padding:7px 10px;border-radius:10px;background:rgba(20,184,166,.1);border:1px solid rgba(20,184,166,.25);color:#99f6e4;font-size:11px;font-weight:700}.member-logout{border:0;background:transparent;color:#94a3b8;cursor:pointer;margin-left:5px}.auth-hidden{display:none!important}';document.head.appendChild(css)}
function closeAnn(){var e=document.getElementById('annOverlay');if(e)e.remove()}
function showAnn(a){if(!a||!a.enabled||(!a.title&&!a.content))return;var key=String(a.updatedAt||a.title+'|'+a.content);if(a.mode!=='always'&&localStorage.getItem(ANN_SEEN)===key)return;build();var type=['info','warning','important'].indexOf(a.type)>=0?a.type:'info',icon=type==='important'?'fa-triangle-exclamation':type==='warning'?'fa-bell':'fa-circle-info';var o=document.createElement('div');o.id='annOverlay';o.className='ann-overlay';o.innerHTML='<div class="ann-card" role="dialog" aria-modal="true"><div class="ann-head"><div class="ann-icon ann-'+type+'"><i class="fa-solid '+icon+'"></i></div><div><div class="ann-title">'+esc(a.title||'INFORMASI KUDAJITU FM')+'</div><div style="font-size:10px;color:#64748b;margin-top:4px;text-transform:uppercase;letter-spacing:.12em">Pengumuman</div></div><button class="ann-x" aria-label="Tutup">×</button></div><div class="ann-content">'+esc(a.content||'')+'</div><div class="ann-actions"><button class="ann-close">✓ Saya Mengerti</button></div></div>';document.body.appendChild(o);o.querySelector('.ann-x').onclick=closeAnn;o.querySelector('.ann-close').onclick=function(){if(a.mode!=='always')localStorage.setItem(ANN_SEEN,key);closeAnn()};o.addEventListener('click',function(e){if(e.target===o)closeAnn()})}
function loadAnnouncement(){annJsonp(ANN_GAS+'?action=announcement',10000).then(function(r){showAnn(r.announcement)}).catch(function(){})}
function getToken(){try{return localStorage.getItem(AUTH_TOKEN)||''}catch(e){return''}}
function setToken(t){try{localStorage.setItem(AUTH_TOKEN,t)}catch(e){}}
function clearToken(){try{localStorage.removeItem(AUTH_TOKEN)}catch(e){}}
function authUrl(action,extra){var q='?action='+encodeURIComponent(action);Object.keys(extra||{}).forEach(function(k){q+='&'+encodeURIComponent(k)+'='+encodeURIComponent(extra[k])});return ANN_GAS+q}
function addMemberChip(user){var host=document.querySelector('header .flex.items-center.gap-2')||document.querySelector('header .flex.items-center');if(!host||document.getElementById('memberChip'))return;var d=document.createElement('span');d.id='memberChip';d.className='member-chip';d.innerHTML='👤 '+esc(user.name||user.username)+' <button class="member-logout" type="button" title="Keluar">Keluar</button>';d.querySelector('button').onclick=logout;host.insertBefore(d,host.firstChild)}
function loginOverlay(){build();if(document.getElementById('authOverlay'))return;var o=document.createElement('div');o.id='authOverlay';o.className='auth-overlay';o.innerHTML='<div class="auth-card"><div style="text-align:center;margin-bottom:20px"><div style="font-size:32px;margin-bottom:8px">🎵</div><div style="font-size:22px;font-weight:800;color:#fff">KUDAJITU FM</div><div style="font-size:12px;color:#94a3b8;margin-top:5px">Login diperlukan untuk request lagu</div></div><label style="font-size:11px;font-weight:800;color:#cbd5e1">USERNAME<input id="memberUsername" class="auth-field" autocomplete="username" placeholder="Username"></label><label style="display:block;font-size:11px;font-weight:800;color:#cbd5e1;margin-top:12px">PASSWORD<input id="memberPassword" type="password" class="auth-field" autocomplete="current-password" placeholder="Password"></label><button id="memberLoginBtn" class="auth-btn" type="button">Masuk</button><div id="memberLoginMsg" class="auth-msg"></div></div>';document.body.appendChild(o);o.querySelector('#memberPassword').addEventListener('keydown',function(e){if(e.key==='Enter')doLogin()});o.querySelector('#memberUsername').addEventListener('keydown',function(e){if(e.key==='Enter')doLogin()});o.querySelector('#memberLoginBtn').onclick=doLogin}
function removeAuthOverlay(){var o=document.getElementById('authOverlay');if(o)o.remove()}
function applyMember(user){removeAuthOverlay();addMemberChip(user);var name=document.getElementById('name');if(name){name.value=user.name||user.username;name.readOnly=true;name.title='Nama mengikuti akun yang sedang login'}var p=document.querySelector('#batchForm p');if(p)p.textContent='Satu lagu per baris. Member terdaftar tidak dibatasi jumlah request.';window.KUDAJITUUser=user}
function doLogin(){var u=document.getElementById('memberUsername').value.trim(),p=document.getElementById('memberPassword').value,b=document.getElementById('memberLoginBtn'),m=document.getElementById('memberLoginMsg');if(!u||!p){m.textContent='Username dan password wajib diisi.';return}b.disabled=true;b.textContent='Memeriksa...';m.textContent='';annJsonp(authUrl('login',{username:u,password:p}),12000).then(function(r){if(!r.success||!r.token)throw Error(r.message||'Login gagal');setToken(r.token);applyMember(r.user)}).catch(function(e){m.textContent=e.message||'Login gagal.'}).finally(function(){b.disabled=false;b.textContent='Masuk'})}
function trySession(){var t=getToken();if(!t){loginOverlay();return}annJsonp(authUrl('session',{token:t}),10000).then(function(r){if(!r.success)throw Error('LOGIN_REQUIRED');applyMember(r.user)}).catch(function(){clearToken();loginOverlay()})}
function logout(){var t=getToken();clearToken();try{annJsonp(authUrl('logout',{token:t}),5000)}catch(e){}location.reload()}
function initAuth(){if(!document.body)return;loginOverlay();trySession()}
window.KUDAJITUAnnouncement={load:loadAnnouncement};window.KUDAJITUAuth={logout:logout};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){loadAnnouncement();initAuth()});else{loadAnnouncement();initAuth()}
setInterval(loadAnnouncement,60000);
})();
