(function(){
'use strict';
var GAS='https://script.google.com/macros/s/AKfycbyUB8drjL1dSJedYjKIKjVc5gzIE3Pe-QS0FF8o1_zU4NkAweGLFquhHLfy1Nt_eITA-Q/exec';
var AUTH_PROXY='/api/auth';
var TOKEN_KEY='kudajitu_member_token_v1';
var ANN_KEY='kudajitu_announcement_seen_v2';
var AUTH_ACTIONS={login:1,session:1,logout:1,forgotpassword:1,changepassword:1};
function getToken(){return localStorage.getItem(TOKEN_KEY)||'';}
function request(action,data,timeout){data=data||{};var isAuth=!!AUTH_ACTIONS[String(action||'').toLowerCase()];if(isAuth){return requestAuth(action,data,timeout);}return new Promise(function(resolve,reject){var query='?action='+encodeURIComponent(action);Object.keys(data).forEach(function(key){query+='&'+encodeURIComponent(key)+'='+encodeURIComponent(data[key]);});var callback='kudaAuth_'+Date.now()+'_'+Math.random().toString(36).slice(2),script=document.createElement('script'),finished=false,limit=timeout||25000,timer=setTimeout(function(){finish();reject(new Error('timeout'));},limit);function cleanup(){setTimeout(function(){try{delete window[callback]}catch(e){window[callback]=undefined;}},1000);}function finish(){if(finished)return;finished=true;clearTimeout(timer);script.remove();cleanup();}window[callback]=function(result){if(finished)return;finish();if(result&&result.success!==false)resolve(result);else reject(new Error(result&&result.message||'Server gagal merespons.'));};script.onerror=function(){if(finished)return;finish();reject(new Error('network error'));};script.src=GAS+query+'&callback='+encodeURIComponent(callback)+'&_='+Date.now();document.head.appendChild(script);});}
function requestAuth(action,data,timeout){var params=new URLSearchParams();params.set('action',String(action||''));Object.keys(data||{}).forEach(function(key){params.set(key,String(data[key]==null?'':data[key]));});var controller=new AbortController(),limit=Math.max(10000,Number(timeout)||20000),timer=setTimeout(function(){controller.abort();},limit);return fetch(AUTH_PROXY+'?'+params.toString(),{method:'GET',credentials:'same-origin',cache:'no-store',signal:controller.signal,headers:{'Accept':'application/json'}}).then(function(response){return response.json().catch(function(){throw new Error('Respons auth tidak valid.');}).then(function(result){if(!response.ok||!result||result.success===false)throw new Error(result&&result.message||'Server auth gagal.');return result;});}).catch(function(error){if(error&&error.name==='AbortError')throw new Error('timeout');throw error;}).finally(function(){clearTimeout(timer);});}
function retry(action,data,timeout){var attempts=3;function run(n){return request(action,data,timeout).catch(function(error){if(n>=attempts)throw error;var delay=2500*Math.pow(2,n-1)+Math.floor(Math.random()*1200);return new Promise(function(resolve){setTimeout(resolve,delay);}).then(function(){return run(n+1);});});}return run(1);}
function installDataReliabilityGuard(){if(window.__kudaDataReliabilityGuard)return;if(typeof window.jsonp==='function'){var originalJsonp=window.jsonp;window.jsonp=function(url,timeout){return originalJsonp(url,Math.max(Number(timeout)||0,25000));};}if(typeof window.withRetry==='function'){window.withRetry=async function(fn,tries){var last;var n=Math.max(1,Number(tries)||3);for(var i=0;i<n;i++){try{return await fn()}catch(e){last=e;if(i<n-1)await new Promise(function(resolve){setTimeout(resolve,2500*Math.pow(2,i)+Math.floor(Math.random()*1200));});}}throw last;};}window.__kudaDataReliabilityGuard=true;}
function installRequestAuthGuard(){if(window.__kudaRequestAuthGuard)return;if(typeof window.jsonp!=='function')return;var originalJsonp=window.jsonp;window.jsonp=function(url,timeout){var isMutation=/[?&]action=(?:add|addBatch)(?:&|$)/i.test(String(url||''));if(isMutation){var mode=String(window.KUDAJITUUserLoginMode||'open').toLowerCase();if(mode==='required'){var token=getToken();if(!token)return Promise.reject(new Error('LOGIN_REQUIRED'));if(!/[?&]token=/.test(String(url||'')))url+='&token='+encodeURIComponent(token);}}return originalJsonp(url,timeout);};if(typeof window.canSubmit==='function'){window.canSubmit=function(count){var now=Date.now();if(now-(window.lastSubmit||0)<5000){if(typeof window.toast==='function')window.toast('Tunggu beberapa detik sebelum request lagi.','error');return false;}var nameEl=document.getElementById('name'),name=nameEl?nameEl.value.trim():'';if(!name){if(typeof window.toast==='function')window.toast('Nama wajib diisi.','error');return false;}return true;};}window.__kudaRequestAuthGuard=true;}
function esc(value){return String(value==null?'':value).replace(/[&<>\"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c];});}
function addStyle(){if(document.getElementById('kuda-auth-style'))return;var style=document.createElement('style');style.id='kuda-auth-style';style.textContent='.auth-overlay{position:fixed;inset:0;z-index:10000;background:rgba(2,8,9,.96);display:flex;align-items:center;justify-content:center;padding:14px}.auth-card{width:min(420px,100%);max-height:calc(100dvh - 28px);overflow:auto;background:#071719;border:1px solid #115e59;border-radius:20px;padding:24px;box-shadow:0 25px 80px #000}.auth-field{box-sizing:border-box;width:100%;background:#030a0c;border:1px solid #115e59;border-radius:11px;padding:12px;color:#fff;margin-top:8px;outline:0;font-size:16px}.auth-btn{width:100%;border:0;border-radius:11px;padding:12px;background:#0d9488;color:#fff;font-weight:800;margin-top:12px;cursor:pointer}.auth-btn:disabled{opacity:.55;cursor:wait}.auth-link{border:0;background:none;color:#5eead4;font-size:11px;cursor:pointer;margin-top:10px}.auth-links{display:flex;justify-content:center;align-items:center;gap:8px;flex-wrap:wrap;margin-top:10px}.auth-link-sep{color:#475569;font-size:11px}.auth-msg{font-size:12px;color:#f87171;margin-top:10px;min-height:18px}.kuda-ann-overlay{position:fixed;inset:0;z-index:9998;background:rgba(0,0,0,.72);backdrop-filter:blur(6px);display:flex;align-items:center;justify-content:center;padding:16px}.kuda-ann-card{width:min(520px,100%);max-height:calc(100dvh - 32px);overflow:auto;background:#071719;border:1px solid rgba(45,212,191,.32);border-radius:22px;padding:22px;box-shadow:0 25px 90px rgba(0,0,0,.8)}.kuda-ann-content{white-space:pre-wrap;word-break:break-word;color:#cbd5e1;line-height:1.7;font-size:13px}.kuda-ann-btn{width:100%;border:0;border-radius:11px;padding:12px;background:#0d9488;color:#fff;font-weight:800;cursor:pointer;margin-top:18px}';document.head.appendChild(style);}
function showAnnouncement(){if(document.getElementById('kudaAnnouncement'))return;request('announcement',{},10000).then(function(result){var a=result&&result.announcement;if(!a||a.enabled!==true||!String(a.title||'').trim()&&!String(a.content||'').trim())return;var version=String(a.updatedAt||'');if(String(a.mode||'once')==='once'&&version&&localStorage.getItem(ANN_KEY)===version)return;addStyle();var overlay=document.createElement('div');overlay.id='kudaAnnouncement';overlay.className='kuda-ann-overlay';overlay.innerHTML='<div class="kuda-ann-card"><b style="color:#fff;font-size:18px">'+esc(a.title||'INFORMASI KUDAJITU FM')+'</b><div class="kuda-ann-content" style="margin-top:12px">'+esc(a.content||'')+'</div><button class="kuda-ann-btn">Mengerti</button></div>';document.body.appendChild(overlay);overlay.querySelector('button').onclick=function(){if(version)localStorage.setItem(ANN_KEY,version);overlay.remove();};}).catch(function(error){console.warn('Announcement:',error.message);});}
window.KUDAAuth={getToken:getToken,currentUser:function(){return window.KUDAJITUUser?Promise.resolve(window.KUDAJITUUser):Promise.reject(new Error('Silakan login terlebih dahulu.'));},validateSession:function(){return window.KUDAJITUUserAccess&&window.KUDAJITUUserAccess.verifySession?window.KUDAJITUUserAccess.verifySession():Promise.reject(new Error('User auth belum siap.'));},showLogin:function(){return window.KUDAJITUUserAccess&&window.KUDAJITUUserAccess.openLogin?window.KUDAJITUUserAccess.openLogin():undefined;},logout:function(){return window.KUDAJITUUserAccess&&window.KUDAJITUUserAccess.logout?window.KUDAJITUUserAccess.logout():undefined;}};
window.addEventListener('DOMContentLoaded',function(){installDataReliabilityGuard();installRequestAuthGuard();addStyle();});
})();