(function(){'use strict';
const URL='https://jdqcvfqysmjreibcaduk.supabase.co',KEY='sb_publishable_QDcyGfH-3dBNmUYE9pKIkg_uFmRsmOa',MAX=20;
let db=null,rows=[],selected=new Set(),loading=false;
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function client(){if(!db)db=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return db}
function norm(v){return String(v||'').trim().toLowerCase().replace(/[‐‑‒–—]/g,'-').replace(/\s+/g,' ')}
function toast(msg,error=false){const e=$('toast');if(e){e.textContent=msg;e.className='fixed right-4 bottom-4 z-50 glass rounded-xl px-4 py-3 text-xs border '+(error?'border-red-700 text-red-300':'border-teal-800 text-teal-200');setTimeout(()=>e.classList.add('hidden'),3200)}}
function filtered(){const q=norm($('search')?.value||'');if(!q)return rows;return rows.filter(r=>norm(r.title+' '+r.artist).includes(q))}
function render(){const list=$('list'),empty=$('empty'),count=$('selectedCount'),btn=$('sendBtn');if(count)count.textContent=String(selected.size);if(btn){btn.disabled=!selected.size||loading;btn.innerHTML=loading?'⏳ Mengirim...':'🎵 Kirim '+selected.size+' Request'}const data=filtered();if(!data.length){list.innerHTML='';empty.classList.remove('hidden');return}empty.classList.add('hidden');list.innerHTML=data.map((r,i)=>{const on=selected.has(r.key);return '<label class="song glass rounded-xl p-3 flex gap-3 items-center cursor-pointer '+(on?'selected':'')+'"><input type="checkbox" class="song-check" data-key="'+esc(r.key)+'" '+(on?'checked':'')+'><div class="min-w-0 flex-1"><div class="font-extrabold text-sm truncate">'+esc(r.title)+'</div><div class="text-xs text-gray-400 truncate">'+esc(r.artist)+'</div></div><a class="text-teal-300 text-xs px-2" href="'+esc(r.youtube_url)+'" target="_blank" rel="noopener" onclick="event.stopPropagation()" title="Lihat YouTube">▶</a></label>'}).join('');list.querySelectorAll('.song-check').forEach(cb=>cb.addEventListener('change',()=>{const k=cb.dataset.key;if(cb.checked){if(selected.size>=MAX){cb.checked=false;toast('Maksimal '+MAX+' lagu per pengiriman.',true);return}selected.add(k)}else selected.delete(k);render() }))}
async function load(){if(loading)return;loading=true;render();try{const c=client();const {data,error}=await c.from('youtube_mappings').select('title,artist,youtube_id,youtube_url').order('title',{ascending:true}).limit(1000);if(error)throw error;rows=(data||[]).filter(r=>r.title&&r.artist&&r.youtube_id).map(r=>({title:String(r.title),artist:String(r.artist),youtube_id:String(r.youtube_id),youtube_url:String(r.youtube_url||('https://www.youtube.com/watch?v='+r.youtube_id)),key:norm(r.title)+'|'+norm(r.artist)}));render();$('statusText').textContent=rows.length+' lagu tersedia';}catch(e){$('statusText').textContent='Gagal memuat katalog';toast('Gagal memuat lagu: '+(e.message||e),true)}finally{loading=false;render()}}
async function currentUser(){try{return(await client().auth.getUser()).data?.user||null}catch(_){return null}}
async function ensureAccess(){const mode=String(window.KUDAJITUUserLoginMode||'open');if(mode==='required'&&typeof window.KUDAJITUUserAccess?.verifySession==='function'){const ok=await window.KUDAJITUUserAccess.verifySession();if(!ok){window.KUDAJITUUserAccess.openLogin?.();return false}}return true}
async function send(){if(loading||!selected.size)return;if(selected.size>MAX)return toast('Maksimal '+MAX+' lagu.',true);if(!await ensureAccess())return;const name=String($('name')?.value||'').trim();if(!name){toast('Isi Nama Kamu terlebih dahulu.',true);$('name')?.focus();return}loading=true;render();try{const u=await currentUser();const chosen=rows.filter(r=>selected.has(r.key));if(chosen.length!==selected.size)throw Error('Sebagian lagu tidak lagi tersedia. Silakan refresh.');const payload=chosen.map(r=>({requester:name,title:r.title,artist:r.artist,note:r.youtube_url,status:'pending',...(u?.id?{created_by:u.id}:{})}));const {error}=await client().from('requests').insert(payload);if(error)throw error;toast(chosen.length+' request berhasil dikirim.');selected.clear();await load();}catch(e){console.error('[Kudajitu Available Songs]',e);toast('Gagal mengirim: '+(e.message||e),true)}finally{loading=false;render()}}
function injectHomeButton(){if(!window.location.pathname.endsWith('/')&&!window.location.pathname.endsWith('/index.html'))return;const box=document.querySelector('#singleForm')?.closest('.glass');if(!box||$('availableSongsBtn'))return;const b=document.createElement('a');b.id='availableSongsBtn';b.href='./available-songs.html';b.className='btn w-full py-2.5 rounded-xl border border-teal-700/60 text-teal-300 font-extrabold text-center mb-3 block';b.innerHTML='<i class="fa-solid fa-music mr-2"></i>Pilih dari Lagu Tersedia';const nameInput=$('name');nameInput?.after(b)}
function boot(){if(!$('list')){setTimeout(boot,40);return}injectHomeButton();$('search')?.addEventListener('input',render);$('sendBtn')?.addEventListener('click',send);load()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();