(function(){'use strict';
const URL='https://jdqcvfqysmjreibcaduk.supabase.co',KEY='sb_publishable_QDcyGfH-3dBNmUYE9pKIkg_uFmRsmOa',MAX=20;
let db=null,rows=[],selected=new Set(),loading=false;
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
function client(){if(!db)db=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return db}
function norm(v){return String(v||'').trim().toLowerCase().replace(/[‐‑‒–—]/g,'-').replace(/\s+/g,' ')}
function toast(msg,error=false){const e=$('toast');if(!e)return;e.className='fixed right-4 bottom-4 z-50 glass rounded-xl px-4 py-3 text-xs border '+(error?'border-red-700 text-red-300':'border-teal-800 text-teal-200');e.textContent=msg;clearTimeout(window.__availToast);window.__availToast=setTimeout(()=>e.classList.add('hidden'),3200)}
function injectHomeButton(){if(!window.location.pathname.endsWith('/')&&!window.location.pathname.endsWith('/index.html'))return;if($('availableSongsBtn'))return;const box=document.querySelector('#singleForm')?.closest('.glass');if(!box)return;const b=document.createElement('a');b.id='availableSongsBtn';b.href='./available-songs.html';b.className='btn w-full py-2.5 rounded-xl border border-teal-700/60 text-teal-300 font-extrabold text-center mb-3 block';b.innerHTML='<i class="fa-solid fa-music mr-2"></i>Pilih dari Lagu Tersedia';$('name')?.after(b)}
function filtered(){const q=norm($('search')?.value||'');if(!q)return rows;return rows.filter(r=>norm(r.title+' '+r.artist).includes(q))}
function showLimitPopup(limit,used,requested){document.getElementById('dailyLimitPopup')?.remove();const remaining=Math.max(0,limit-used),m=document.createElement('div');m.id='dailyLimitPopup';m.style.cssText='position:fixed;inset:0;z-index:1500;background:rgba(0,0,0,.78);backdrop-filter:blur(9px);display:flex;align-items:center;justify-content:center;padding:16px';const full=requested>remaining;m.innerHTML=`<div style="width:min(420px,100%);background:#071719;border:1px solid rgba(45,212,191,.28);border-radius:22px;padding:22px;box-shadow:0 30px 100px rgba(0,0,0,.68)"><div style="display:flex;justify-content:center"><div style="width:62px;height:62px;border-radius:18px;background:rgba(239,68,68,.12);border:1px solid rgba(248,113,113,.3);display:flex;align-items:center;justify-content:center;font-size:28px">🚫</div></div><div style="text-align:center;margin-top:14px;font-size:17px;font-weight:900;color:#fff">Batas Request Harian</div><div style="text-align:center;color:#94a3b8;font-size:11px;line-height:1.6;margin-top:7px">${full?`Kamu mencoba mengirim <b style="color:#fff">${requested} lagu</b>, tetapi kuota kamu tersisa <b style="color:#fbbf24">${remaining} lagu</b> hari ini.`:'Kamu sudah mencapai batas request lagu hari ini.'}</div><div style="margin-top:16px;padding:13px;border-radius:14px;background:#030a0c;border:1px solid #115e59;text-align:center"><div style="font-size:10px;color:#64748b">REQUEST HARI INI</div><div style="font-size:24px;font-weight:900;color:#f87171;margin-top:3px">${used} / ${limit}</div><div style="font-size:10px;color:#64748b;margin-top:3px">Tersisa ${remaining} request</div></div><div style="text-align:center;font-size:10px;color:#64748b;margin-top:12px">Kuota akan tersedia kembali besok.</div><button id="dailyLimitClose" type="button" style="width:100%;margin-top:14px;border:0;border-radius:11px;padding:12px;background:#0d9488;color:#fff;font-weight:900;cursor:pointer">Mengerti</button></div>`;document.body.appendChild(m);m.querySelector('#dailyLimitClose').onclick=()=>m.remove();m.addEventListener('click',e=>{if(e.target===m)m.remove()})}
async function getDailyQuota(u){if(!u?.id)return{limit:0,used:0,remaining:Infinity};const {data:p,error:pe}=await client().from('user_profiles').select('daily_request_limit').eq('id',u.id).maybeSingle();if(pe)throw pe;const limit=Number(p?.daily_request_limit||0);if(limit<=0)return{limit:0,used:0,remaining:Infinity};const start=new Date();start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+1);const {count,error}=await client().from('requests').select('id',{count:'exact',head:true}).eq('created_by',u.id).gte('timestamp',start.toISOString()).lt('timestamp',end.toISOString());if(error)throw error;const used=Number(count||0);return{limit,used,remaining:Math.max(0,limit-used)}}
function limitInfo(limit,used){if(limit<=0)return'Unlimited';const remaining=Math.max(0,limit-used);return`Request hari ini: ${used}/${limit} • sisa ${remaining}`}
async function renderQuota(){const u=await currentUser();if(!u)return;try{const q=await getDailyQuota(u);let el=$('dailyQuotaInfo');if(!el){el=document.createElement('p');el.id='dailyQuotaInfo';el.className='text-[10px] text-gray-500 mt-2';$('statusText')?.after(el)}el.textContent=limitInfo(q.limit,q.used);if(q.limit>0&&q.remaining===0)el.style.color='#f87171'}catch(e){console.warn('[Kudajitu quota]',e)}}
function render(){const list=$('list');if(!list)return;const empty=$('empty'),count=$('selectedCount'),btn=$('sendBtn');if(count)count.textContent=String(selected.size);if(btn){btn.disabled=!selected.size;btn.innerHTML='🎵 Kirim '+selected.size+' Request'}const data=filtered();if(!data.length){list.innerHTML='';empty?.classList.remove('hidden');return}empty?.classList.add('hidden');list.innerHTML=data.map(r=>{const on=selected.has(r.key);return '<label class="song glass rounded-xl p-3 flex gap-3 items-center cursor-pointer '+(on?'selected':'')+'"><input type="checkbox" class="song-check" data-key="'+esc(r.key)+'" '+(on?'checked':'')+'><div class="min-w-0 flex-1"><div class="font-extrabold text-sm truncate">'+esc(r.title)+'</div><div class="text-xs text-gray-400 truncate">'+esc(r.artist)+'</div></div><a class="text-teal-300 text-xs px-2" href="'+esc(r.youtube_url)+'" target="_blank" rel="noopener" onclick="event.stopPropagation()" title="Lihat YouTube">▶</a></label>'}).join('');list.querySelectorAll('.song-check').forEach(cb=>cb.addEventListener('change',()=>{const k=cb.dataset.key;if(cb.checked){if(selected.size>=MAX){cb.checked=false;toast('Maksimal '+MAX+' lagu per pengiriman.',true);return}selected.add(k)}else selected.delete(k);render()}))}
async function load(){try{const {data,error}=await client().from('youtube_mappings').select('title,artist,youtube_id,youtube_url').order('title',{ascending:true}).limit(1000);if(error)throw error;const seen=new Set();rows=(data||[]).filter(r=>r.title&&r.artist&&r.youtube_id).map(r=>({title:String(r.title),artist:String(r.artist),youtube_id:String(r.youtube_id),youtube_url:String(r.youtube_url||('https://www.youtube.com/watch?v='+r.youtube_id)),key:norm(r.title)+'|'+norm(r.artist)})).filter(r=>!seen.has(r.key)&&(seen.add(r.key),true));$('statusText').textContent=rows.length+' lagu tersedia';render();renderQuota()}catch(e){$('statusText').textContent='Gagal memuat katalog';toast('Gagal memuat lagu: '+(e.message||e),true)}finally{loading=false;render()}}
async function currentUser(){try{return(await client().auth.getUser()).data?.user||null}catch(_){return null}}
async function ensureAccess(){const mode=String(window.KUDAJITUUserLoginMode||'open');if(mode==='required'&&typeof window.KUDAJITUUserAccess?.verifySession==='function'){const ok=await window.KUDAJITUUserAccess.verifySession();if(!ok){window.KUDAJITUUserAccess.openLogin?.();return false}}return true}
async function send(){if(loading||!selected.size)return;if(selected.size>MAX)return toast('Maksimal '+MAX+' lagu.',true);if(!await ensureAccess())return;const name=String($('name')?.value||'').trim();if(!name){toast('Isi Nama Kamu terlebih dahulu.',true);$('name')?.focus();return}const chosen=rows.filter(r=>selected.has(r.key));if(chosen.length!==selected.size){toast('Sebagian lagu sudah tidak tersedia. Silakan refresh.',true);return}loading=true;render();try{const u=await currentUser();const quota=await getDailyQuota(u);if(quota.limit>0&&quota.used>=quota.limit){selected.clear();showLimitPopup(quota.limit,quota.used,chosen.length);return}if(quota.limit>0&&chosen.length>quota.remaining){showLimitPopup(quota.limit,quota.used,chosen.length);return}const payload=chosen.map(r=>({requester:name,title:r.title,artist:r.artist,note:r.youtube_url,status:'pending',...(u?.id?{created_by:u.id}:{})}));const {error}=await client().from('requests').insert(payload);if(error){const msg=String(error.message||error||'');if(msg.toUpperCase().includes('DAILY_REQUEST_LIMIT')||msg.toLowerCase().includes('batas request harian')){showLimitPopup(quota.limit,quota.used,chosen.length);return}throw error}toast(chosen.length+' request berhasil dikirim.');selected.clear();await load()}catch(e){console.error('[Kudajitu Available Songs]',e);toast('Gagal mengirim: '+(e.message||e),true)}finally{loading=false;render()}}
function boot(){injectHomeButton();if(!$('list'))return;$('search')?.addEventListener('input',render);$('sendBtn')?.addEventListener('click',send);load()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
