(function(){'use strict';
const state={mode:'all'};
function statusOf(card){const t=(card.innerText||'').toLowerCase();if(t.includes('selesai'))return'done';if(t.includes('diproses')||t.includes('proses'))return'process';if(t.includes('ditolak')||t.includes('tolak'))return'reject';return'waiting';}
function featureStatus(){const f=document.querySelector('#myRequestsSection .myreq-feature');return f?statusOf(f):null;}
function filterMine(){const section=document.getElementById('myRequestsSection');if(!section)return;const cards=section.querySelectorAll('.myreq-card');cards.forEach(c=>{const s=statusOf(c);let show=state.mode==='all'||(state.mode==='waiting'&&s==='waiting')||(state.mode==='done'&&s==='done');c.style.display=show?'':'none';});const feature=section.querySelector('.myreq-feature');if(feature){const s=statusOf(feature);let show=state.mode==='all'||(state.mode==='waiting'&&s==='waiting')||(state.mode==='done'&&s==='done');feature.style.display=show?'':'none';}
const visible=Array.from(cards).filter(c=>c.style.display!=='none').length;let empty=section.querySelector('.myreq-filter-empty');if(!visible&&!feature||!visible){if(!empty){empty=document.createElement('div');empty.className='myreq-filter-empty';empty.style='padding:14px;text-align:center;color:#64748b;font-size:10px;border:1px dashed #16413e;border-radius:10px;margin-top:8px;';section.querySelector('.myreq-list')?.appendChild(empty);}empty.textContent=state.mode==='waiting'?'Belum ada request yang masih dalam antrean.':state.mode==='done'?'Belum ada request yang selesai.':'Belum ada request.';}else if(empty)empty.remove();}
function setMode(mode){state.mode=mode;filterMine();}
function findTabs(){const section=document.getElementById('myRequestsSection');if(!section)return;let root=section.parentElement;for(let i=0;i<4&&root;i++,root=root.parentElement){const buttons=Array.from(root.querySelectorAll('button,[role="button"]')).filter(b=>['semua','antrean','selesai'].includes((b.textContent||'').trim().toLowerCase()));if(buttons.length>=2)return buttons;}return[];}
function bindTabs(){const tabs=findTabs();if(!tabs.length)return;tabs.forEach(btn=>{if(btn.dataset.kudaFilterBound)return;btn.dataset.kudaFilterBound='1';btn.addEventListener('click',function(){const text=(btn.textContent||'').trim().toLowerCase();if(text==='semua')setMode('all');else if(text==='antrean')setMode('waiting');else if(text==='selesai')setMode('done');setTimeout(filterMine,30);});});}
function syncFromActive(){const tabs=findTabs();if(!tabs.length)return;const active=tabs.find(b=>{const c=b.className||'';return /active|selected|on|primary/i.test(c)||b.getAttribute('aria-selected')==='true';});if(!active)return;const t=(active.textContent||'').trim().toLowerCase();if(t==='semua')state.mode='all';else if(t==='antrean')state.mode='waiting';else if(t==='selesai')state.mode='done';filterMine();}
function style(){if(document.getElementById('kuda-request-filter-style'))return;const s=document.createElement('style');s.id='kuda-request-filter-style';s.textContent='.myreq-filter-empty{margin-top:8px}.myreq-feature[style*="display: none"]{margin:0!important}';document.head.appendChild(s);}
function init(){style();bindTabs();syncFromActive();filterMine();const obs=new MutationObserver(function(){bindTabs();filterMine();});obs.observe(document.body,{childList:true,subtree:true});setInterval(function(){bindTabs();syncFromActive();},1000);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
