(function(){'use strict';
/* Safe Request Saya filter: event-driven only. Uses explicit data-status attributes and !important display to avoid CSS conflicts. */
let mode='all';
function statusOf(el){if(!el)return'waiting';const badge=el.querySelector('.myreq-status,.myreq-feature-status');const t=(badge?badge.textContent:el.getAttribute('data-status')||'').toLowerCase().replace(/\s+/g,' ').trim();if(t.includes('ditolak')||t.includes('tolak'))return'reject';if(t.includes('selesai')||t.includes('played'))return'done';if(t.includes('diproses')||t.includes('proses'))return'process';return'waiting';}
function apply(){const section=document.getElementById('myRequestsSection');if(!section)return;const feature=section.querySelector('.myreq-feature');const cards=section.querySelectorAll('.myreq-card');const items=[];if(feature)items.push(feature);for(let i=0;i<cards.length;i++)items.push(cards[i]);let visible=0;for(let i=0;i<items.length;i++){const el=items[i];const s=statusOf(el);const show=mode==='all'||(mode==='waiting'&&s==='waiting')||(mode==='done'&&s==='done');el.setAttribute('data-filter-status',s);el.style.setProperty('display',show?'':'none','important');if(show)visible++;}
let empty=section.querySelector('.myreq-filter-empty');if(!visible){if(!empty){empty=document.createElement('div');empty.className='myreq-filter-empty';empty.style='padding:14px;text-align:center;color:#64748b;font-size:10px;border:1px dashed #16413e;border-radius:10px;margin-top:8px;';const list=section.querySelector('.myreq-list');if(list)list.appendChild(empty);}empty.textContent=mode==='waiting'?'Belum ada request yang masih dalam antrean.':mode==='done'?'Belum ada request yang selesai.':'Belum ada request.';}else if(empty)empty.remove();}
function applySoon(){apply();[100,250,500,900,1400,2000].forEach(ms=>setTimeout(apply,ms));}
function setMode(next){mode=next;applySoon();}
function handleClick(e){const btn=e.target&&e.target.closest?e.target.closest('button'):null;if(!btn||btn.closest('#myRequestsSection'))return;const label=(btn.textContent||'').replace(/\s+/g,' ').trim().toLowerCase();if(label==='semua')setMode('all');else if(label==='antrean')setMode('waiting');else if(label==='selesai')setMode('done');}
function init(){document.addEventListener('click',handleClick,false);setTimeout(apply,500);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
