(function(){
'use strict';
const GAS='https://script.google.com/macros/s/AKfycbyUB8drjL1dSJedYjKIKjVc5gzIE3Pe-QS0FF8o1_zU4NkAweGLFquhHLfy1Nt_eITA-Q/exec';
const USER_TOKEN_KEY='kudajitu_user_token';
let loginMode='open';
let modeLoaded=false;
let authUser=null;
const $=id=>document.getElementById(id);
function jsonp(url,timeout=9000){return new Promise((resolve,reject)=>{const cb='__kuda_access_'+Date.now()+'_'+Math.random().toString(36).slice(2),s=document.createElement('script');let done=false;const timer=setTimeout(()=>finish(Error('Timeout')),timeout);function finish(err,data){if(done)return;done=true;clearTimeout(timer);s.remove();try{delete window[cb]}catch(e){}err?reject(err):resolve(data)}window[cb]=d=>d&&d.success!==false?finish(null,d):finish(Error(d&&d.message||'Server gagal'));s.src=url+(url.includes('?')?'&':'?')+'callback='+cb+'&_='+Date.now();s.onerror=()=>finish(Error('Network error'));document.head.appendChild(s)})}
function token(){return sessionStorage.getItem(USER_TOKEN_KEY)||localStorage.getItem(USER_TOKEN_KEY)||'';}
function getMode(){return loginMode;}
function setModeUi(mode){loginMode=mode==='required'?'required':'open';modeLoaded=true;const form=document.getElementById('singleForm')||document.getElementById('batchForm');const card=form&&form.closest('.glass');let gate=document.getElementById('userAccessGate');if(loginMode==='open'){if(gate)gate.remove();if(form)form.classList.remove('hidden');return;}if(!gate&&card){gate=document.createElement('div');gate.id='userAccessGate';gate.className='rounded-xl border border-amber-800/60 bg-amber-950/30 p-4 mb-4 text-sm';card.insertBefore(gate,form||card.firstChild);}if(gate){gate.innerHTML=authUser?'<b class="text-teal-300">✓ Login User aktif</b><p class="text-xs text-gray-400 mt-1">'+escapeHtml(authUser.name||authUser.username||'User')+' sudah login.</p><button type="button" id="userLogoutBtn" class="btn mt-3 bg-gray-950 border border-teal-800">Keluar</button>':'<b class="text-amber-300">🔒 Login diperlukan</b><p class="text-xs text-gray-400 mt-1">Admin sedang mewajibkan login sebelum request.</p><button type="button" id="userLoginBtn" class="btn mt-3 bg-teal-600">Login User</button>';$('userLoginBtn')?.addEventListener('click',openLogin);$('userLogoutBtn')?.addEventListener('click',logout);}
function escapeHtml(v){return String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function openLogin(){let m=document.getElementById('userLoginModal');if(m)return;m=document.createElement('div');m.id='userLoginModal';m.className='fixed inset-0 z-[60] bg-black/80 flex items-center justify-center p-4';m.innerHTML='<div class="glass rounded-2xl p-6 w-full max-w-sm"><div class="flex justify-between items-center mb-4"><b>Login User</b><button type="button" id="userCloseBtn" class="btn">✕</button></div><input id="userLoginUsername" class="field mb-3" placeholder="Username" autocomplete="username"><input id="userLoginPassword" type="password" class="field mb-3" placeholder="Password" autocomplete="current-password"><button id="userLoginSubmit" type="button" class="btn w-full bg-teal-600 text-white">Masuk</button><p id="userLoginMsg" class="text-xs text-red-400 mt-3"></p></div>';document.body.appendChild(m);m.querySelector('#userCloseBtn').onclick=()=>m.remove();m.querySelector('#userLoginSubmit').onclick=login;}
async function login(){const u=$('userLoginUsername')?.value.trim()||'',p=$('userLoginPassword')?.value||'',msg=$('userLoginMsg');if(!u||!p){if(msg)msg.textContent='Username dan password wajib diisi.';return;}const btn=$('userLoginSubmit');if(btn){btn.disabled=true;btn.textContent='Memeriksa...';}try{const r=await jsonp(GAS+'?action=login&username='+encodeURIComponent(u)+'&password='+encodeURIComponent(p),12000);if(!r.success)throw Error(r.message||'Login gagal.');authUser=r.user||null;sessionStorage.setItem(USER_TOKEN_KEY,r.token);localStorage.setItem(USER_TOKEN_KEY,r.token);document.getElementById('userLoginModal')?.remove();setModeUi('required');enableSubmit(true);}catch(e){if(msg)msg.textContent=e.message;}finally{if(btn){btn.disabled=false;btn.textContent='Masuk';}}}
async function verifySession(){const t=token();if(!t)return false;try{const r=await jsonp(GAS+'?action=session&token='+encodeURIComponent(t),8000);if(r.success){authUser=r.user||null;return true;}}catch(e){}sessionStorage.removeItem(USER_TOKEN_KEY);localStorage.removeItem(USER_TOKEN_KEY);authUser=null;return false;}
async function logout(){const t=token();try{if(t)await jsonp(GAS+'?action=logout&token='+encodeURIComponent(t),7000);}catch(e){}sessionStorage.removeItem(USER_TOKEN_KEY);localStorage.removeItem(USER_TOKEN_KEY);authUser=null;setModeUi(loginMode);enableSubmit(false);}
function enableSubmit(allowed){const buttons=document.querySelectorAll('#singleForm button[type="submit"],#batchForm button[type="submit"]');buttons.forEach(b=>{if(allowed===false&&loginMode==='required')b.disabled=true;else b.disabled=false;});}
function patchRequestSubmit(){['addSingle','addBatch'].forEach(name=>{if(typeof window[name]!=='function'||window['__accessWrapped_'+name])return;const original=window[name];window[name]=function(event){if(loginMode==='required'&&!authUser){event&&event.preventDefault();openLogin();return false;}return original.call(this,event);};window['__accessWrapped_'+name]=true;});}
async function loadMode(){try{const r=await jsonp(GAS+'?action=userloginmode',8000);setModeUi(r.mode||'open');if(loginMode==='required'){const ok=await verifySession();setModeUi('required');enableSubmit(ok);}else{const t=token();if(t)await verifySession();enableSubmit(true);}}catch(e){setModeUi('open');enableSubmit(true);}patchRequestSubmit();}
function observe(){const obs=new MutationObserver(()=>{patchRequestSubmit();if(modeLoaded)setModeUi(loginMode);});obs.observe(document.body,{childList:true,subtree:true});}
function init(){observe();setTimeout(loadMode,250);setTimeout(loadMode,1800);}
window.kudajituUserAccess={loadMode,openLogin,logout,getMode};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();