(function(){'use strict';
const GAS='/api/gas';
const TOKEN_KEYS=['kudajitu_member_token_v1','kudajitu_user_token'];
let loginMode='open',authUser=null;
const $=id=>document.getElementById(id);
function jsonp(url,timeout=15000){return new Promise((resolve,reject)=>{const cb='__kuda_access_'+Date.now()+'_'+Math.random().toString(36).slice(2),s=document.createElement('script');let done=false;const timer=setTimeout(()=>finish(Error('Timeout')),timeout);function finish(err,data){if(done)return;done=true;clearTimeout(timer);s.remove();try{delete window[cb]}catch(e){}err?reject(err):resolve(data)}window[cb]=d=>d&&d.success!==false?finish(null,d):finish(Error(d&&d.message||'Server gagal'));s.src=url+(url.includes('?')?'&':'?')+'callback='+cb+'&_='+Date.now();s.onerror=()=>finish(Error('Network error'));document.head.appendChild(s)})}
function token(){try{for(const k of TOKEN_KEYS){const v=sessionStorage.getItem(k)||localStorage.getItem(k);if(v)return v}}catch(e){}return''}
function setToken(v){try{TOKEN_KEYS.forEach(k=>{if(v){sessionStorage.setItem(k,v);localStorage.setItem(k,v)}else{sessionStorage.removeItem(k);localStorage.removeItem(k)}})}catch(e){}}
function accessUrl(action,params){const q=new URLSearchParams(params||{});q.set('action',action);const t=token();if(t)q.set('token',t);return GAS+'?'+q.toString()}
function getMode(){return loginMode}
function header(){return document.querySelector('header>div>div:last-child')}
function requestCard(){const f=$('singleForm')||$('batchForm');return f?f.closest('.glass'):null}
function addStyle(){if($('kuda-user-style'))return;const s=document.createElement('style');s.id='kuda-user-style';s.textContent='.kuda-login-chip,.kuda-member-chip{display:inline-flex!important;align-items:center;justify-content:center;white-space:nowrap;border-radius:10px;padding:7px 10px;font-size:10px;font-weight:800;cursor:pointer;max-width:150px;overflow:hidden;text-overflow:ellipsis;order:3;margin-left:0}.kuda-login-chip{background:#0d9488;border:1px solid #2dd4bf;color:#fff}.kuda-member-chip{background:#071719;border:1px solid #115e59;color:#99f6e4}.kuda-account-menu{position:fixed;right:12px;top:68px;z-index:10001;width:min(330px,calc(100vw - 24px));background:#071719;border:1px solid #115e59;border-radius:16px;padding:16px;box-shadow:0 20px 60px #000}.kuda-auth-overlay{position:fixed;inset:0;z-index:10000;background:rgba(2,8,9,.96);display:flex;align-items:center;justify-content:center;padding:14px}.kuda-auth-card{width:min(420px,100%);max-height:calc(100dvh - 28px);overflow:auto;background:#071719;border:1px solid #115e59;border-radius:20px;padding:24px;box-shadow:0 25px 80px #000}.kuda-auth-field{box-sizing:border-box;width:100%;background:#030a0c;border:1px solid #115e59;border-radius:11px;padding:12px;color:#fff;margin-top:8px;outline:0;font-size:16px}.kuda-auth-btn{width:100%;border:0;border-radius:11px;padding:12px;background:#0d9488;color:#fff;font-weight:800;margin-top:12px;cursor:pointer}.kuda-auth-msg{font-size:12px;color:#f87171;margin-top:10px;min-height:18px}.kuda-auth-link{border:0;background:none;color:#5eead4;font-size:11px;cursor:pointer;margin-top:10px}.kuda-auth-links{display:flex;justify-content:center;gap:8px;flex-wrap:wrap;margin-top:10px}.kuda-request-lock{position:relative}.kuda-request-lock-overlay{position:absolute;inset:0;z-index:20;display:flex;align-items:center;justify-content:center;text-align:center;padding:24px;border-radius:16px;background:rgba(3,10,12,.86);backdrop-filter:blur(5px)}.kuda-request-lock-box{width:min(300px,100%);padding:18px;border:1px solid rgba(45,212,191,.22);border-radius:16px;background:rgba(7,23,25,.96);box-shadow:0 18px 50px rgba(0,0,0,.35)}.kuda-request-lock-box i{font-size:24px;color:#2dd4bf;margin-bottom:9px}.kuda-request-lock-title{font-size:14px;font-weight:800;color:#fff}.kuda-request-lock-text{font-size:11px;color:#94a3b8;margin-top:5px;line-height:1.5}.kuda-request-lock-btn{margin-top:12px;border:0;border-radius:10px;padding:9px 16px;background:#0d9488;color:#fff;font-size:11px;font-weight:800;cursor:pointer}.kuda-request-lock-btn:hover{filter:brightness(1.08)}';document.head.appendChild(s)}
function removeAccountMenu(){document.querySelectorAll('.kuda-account-menu').forEach(m=>m.remove())}
function clearAccountControls(){document.querySelectorAll('#kudaLoginBtn,.kuda-login-chip,#kudaAccountBtn,.kuda-member-chip').forEach(el=>el.remove());removeAccountMenu()}
function showLoginButton(){addStyle();clearAccountControls();const b=document.createElement('button');b.id='kudaLoginBtn';b.type='button';b.className='kuda-login-chip';b.innerHTML='<i class="fa-solid fa-right-to-bracket mr-1"></i> Login';b.onclick=openLogin;const h=header();if(h)h.appendChild(b)}
function showAccount(user){addStyle();clearAccountControls();const b=document.createElement('button');b.id='kudaAccountBtn';b.type='button';b.className='kuda-member-chip';b.title='Akun '+(user.name||user.username||'User');b.textContent='@ '+(user.name||user.username||'User');b.onclick=()=>{let m=$('kudaAccountMenu');if(m){m.remove();return}m=document.createElement('div');m.id='kudaAccountMenu';m.className='kuda-account-menu';m.innerHTML='<b style="color:#fff">Akun</b><div style="font-size:11px;color:#94a3b8;margin:6px 0 12px">@'+escapeHtml(user.username||user.name||'User')+'</div><button id="kudaChangePw" class="kuda-auth-btn">Ganti Password</button><button id="kudaLogout" class="kuda-auth-btn" style="background:#123033">Keluar</button>';document.body.appendChild(m);$('kudaChangePw').onclick=()=>{m.remove();changePassword()};$('kudaLogout').onclick=logout};const h=header();if(h)h.appendChild(b);const name=$('name');if(name){name.value=user.name||user.username||'';name.readOnly=true;name.classList.add('bg-gray-950/70')}}
function escapeHtml(v){return String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function openLogin(){addStyle();if($('kudaAuthOverlay'))return;const o=document.createElement('div');o.id='kudaAuthOverlay';o.className='kuda-auth-overlay';o.innerHTML='<div class="kuda-auth-card"><div style="text-align:center;color:#fff;font-size:22px;font-weight:800;margin-bottom:5px">KUDAJITU FM</div><div style="text-align:center;color:#94a3b8;font-size:11px;margin-bottom:16px">Login untuk mengirim request lagu</div><input id="kudaUser" class="kuda-auth-field" autocomplete="username" placeholder="Username"><input id="kudaPass" type="password" class="kuda-auth-field" autocomplete="current-password" placeholder="Password"><button id="kudaLoginSubmit" class="kuda-auth-btn">Masuk</button><div class="kuda-auth-links"><button id="kudaForgot" class="kuda-auth-link">Lupa password?</button><span style="color:#475569;font-size:11px">•</span><button id="kudaRegister" class="kuda-auth-link">Daftar</button></div><div id="kudaAuthMsg" class="kuda-auth-msg"></div></div>';document.body.appendChild(o);$('kudaLoginSubmit').onclick=login;$('kudaPass').onkeydown=e=>{if(e.key==='Enter')login()};$('kudaForgot').onclick=()=>alert('Silakan hubungi Admin untuk reset password.');$('kudaRegister').onclick=()=>{location.href='register.html'}}
function lockRequestArea(locked){addStyle();const card=requestCard();if(!card)return;card.classList.add('kuda-request-lock');let overlay=$('kudaRequestLock');if(locked){if(overlay)return;overlay=document.createElement('div');overlay.id='kudaRequestLock';overlay.className='kuda-request-lock-overlay';overlay.innerHTML='<div class="kuda-request-lock-box"><i class="fa-solid fa-lock"></i><div class="kuda-request-lock-title">Login diperlukan</div><div class="kuda-request-lock-text">Admin mewajibkan login sebelum kamu dapat mengirim request lagu.</div><button type="button" class="kuda-request-lock-btn"><i class="fa-solid fa-right-to-bracket mr-1"></i> Login User</button></div>';overlay.querySelector('button').onclick=openLogin;card.appendChild(overlay)}else if(overlay){overlay.remove()}}
async function login(){const u=$('kudaUser')?.value.trim()||'',p=$('kudaPass')?.value||'',msg=$('kudaAuthMsg'),b=$('kudaLoginSubmit');if(!u||!p){if(msg)msg.textContent='Username dan password wajib diisi.';return}b.disabled=true;b.textContent='Memeriksa...';try{const r=await jsonp(GAS+'?action=login&username='+encodeURIComponent(u)+'&password='+encodeURIComponent(p),20000);if(!r.success||!r.token)throw Error(r.message||'Login gagal.');authUser=r.user||{};setToken(r.token);window.KUDAJITUUser=authUser;const o=$('kudaAuthOverlay');if(o)o.remove();showAccount(authUser);lockRequestArea(false);enableSubmit(true);window.dispatchEvent(new CustomEvent('kudajitu-user-auth',{detail:{user:authUser}}))}catch(e){if(msg)msg.textContent=e.message||'Login gagal'}finally{b.disabled=false;b.textContent='Masuk'}}
async function verifySession(){const t=token();if(!t){authUser=null;window.KUDAJITUUser=null;return false}try{const r=await jsonp(accessUrl('session'),10000);if(r&&r.success&&r.user){authUser=r.user;window.KUDAJITUUser=authUser;showAccount(authUser);return true}}catch(e){}setToken('');authUser=null;window.KUDAJITUUser=null;return false}
async function logout(){const t=token();removeAccountMenu();setToken('');authUser=null;window.KUDAJITUUser=null;clearAccountControls();try{if(t)await jsonp(GAS+'?action=logout&token='+encodeURIComponent(t),8000)}catch(e){}if(loginMode==='required')showLoginButton();lockRequestArea(loginMode==='required');enableSubmit(false);window.dispatchEvent(new CustomEvent('kudajitu-user-auth',{detail:{user:null}}))}
function enableSubmit(allowed){document.querySelectorAll('#singleForm button[type="submit"],#batchForm button[type="submit"]').forEach(b=>b.disabled=(loginMode==='required'&&!allowed))}
function patchRequestSubmit(){['addSingle','addBatch'].forEach(name=>{if(typeof window[name]!=='function'||window['__accessWrapped_'+name])return;const original=window[name];window[name]=function(event){if(loginMode==='required'&&!authUser){event&&event.preventDefault();openLogin();lockRequestArea(true);return false}return original.call(this,event)};window['__accessWrapped_'+name]=true})}
async function loadMode(){try{const r=await jsonp(GAS+'?action=userloginmode',10000);loginMode=String(r.mode||'open').toLowerCase()==='required'?'required':'open'}catch(e){loginMode='open'}const ok=await verifySession();const locked=loginMode==='required'&&!ok;lockRequestArea(locked);if(locked)showLoginButton();else if(loginMode==='open'&&!ok)clearAccountControls();enableSubmit(!locked);patchRequestSubmit()}
function changePassword(){alert('Fitur ganti password tersedia melalui menu akun.')}
function observe(){const obs=new MutationObserver(()=>{patchRequestSubmit();if(loginMode==='required'&&!authUser)lockRequestArea(true)});obs.observe(document.body,{childList:true,subtree:true})}
function init(){observe();setTimeout(loadMode,150)}
window.KUDAJITUUserAccess={loadMode,openLogin,logout,getMode,verifySession,token};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();