const GAS='https://script.google.com/macros/s/AKfycbyUB8drjL1dSJedYjKIKjVc5gzIE3Pe-QS0FF8o1_zU4NkAweGLFquhHLfy1Nt_eITA-Q/exec';
const READ_ACTIONS=new Set(['data','announcement','health','userloginmode','getqueueorder','checkids']);
const QUEUE_WRITE_ACTIONS=new Set(['add','addbatch','updatestatus','markplayed','updatestatuses','delete','deletebatch','reorder','setqueueorder']);
const ALLOWED_ACTIONS=new Set(['data','announcement','health','add','addbatch','check','checkids','updatestatus','markplayed','updatestatuses','delete','deletebatch','reorder','getqueueorder','setqueueorder','youtubemappings','saveyoutubemapping','deleteyoutubemapping','userloginmode','setuserloginmode','users','saveuser','deleteuser','adminresetpassword','saveannouncement','clearannouncement','login','session','logout','adminlogin','adminsession','adminlogout','forgotpassword','changepassword']);
function parseUpstream(text){const raw=String(text||'').trim();try{return JSON.parse(raw)}catch(_){}const m=raw.match(/^[^(]+\((.*)\)\s*;?\s*$/s);if(m)try{return JSON.parse(m[1])}catch(_){}return null}
function cacheKey(request){const u=new URL(request.url);['callback','prefix','_','_refresh'].forEach(k=>u.searchParams.delete(k));return new Request(u.toString(),{method:'GET'})}
function jsonp(cb,data){const safe=String(cb||'').replace(/[^a-zA-Z0-9_.$]/g,'')||'__kudajituCallback';return new Response(safe+'('+JSON.stringify(data)+');',{headers:{'Content-Type':'application/javascript; charset=utf-8','Cache-Control':'no-store'}})}
function headers(cache,extra){return Object.assign({'Cache-Control':cache?'public, max-age=0, s-maxage=5, stale-while-revalidate=15':'no-store, no-cache, must-revalidate','X-Kuda-API':'v5'},extra||{})}
async function purgeQueueCache(request){
 const cache=caches.default,base=new URL(request.url);
 const ranges=['today','yesterday','all'],statuses=['','pending','played'];
 const keys=[];
 for(const range of ranges){for(const status of statuses){let path='/api/gas?action=data&range='+encodeURIComponent(range);if(status)path+='&status='+encodeURIComponent(status);keys.push(new Request(new URL(path,base).toString()));}}
 await Promise.all(keys.map(key=>cache.delete(key)));
}
function normalizeAction(incoming){const action=String(incoming.searchParams.get('action')||'data').trim().toLowerCase();if(action==='reorder')return'setqueueorder';return action}
function normalizeTargetParams(incoming,action){const params=new URLSearchParams();incoming.searchParams.forEach((v,k)=>{if(!['callback','prefix','_'].includes(k))params.append(k,v)});if(action==='setqueueorder'&&incoming.searchParams.has('ids')&&!incoming.searchParams.has('order')){const ids=String(incoming.searchParams.get('ids')||'').split(',').map(x=>x.trim()).filter(Boolean);params.delete('ids');params.set('order',JSON.stringify(ids));}params.set('action',action);return params}
export async function onRequestGet({request}){
 const started=Date.now(),incoming=new URL(request.url),requestedAction=String(incoming.searchParams.get('action')||'data').trim().toLowerCase(),action=normalizeAction(incoming),cb=incoming.searchParams.get('callback')||incoming.searchParams.get('prefix')||'';
 if(!ALLOWED_ACTIONS.has(requestedAction))return cb?jsonp(cb,{success:false,message:'Action tidak diizinkan.'}):Response.json({success:false,message:'Action tidak diizinkan.'},{status:400,headers:headers(false)});
 const isRead=READ_ACTIONS.has(action),cache=caches.default,key=cacheKey(request),forceFresh=incoming.searchParams.has('_refresh');
 if(isRead&&!forceFresh){const hit=await cache.match(key);if(hit){const t=await hit.text(),b=parseUpstream(t);if(b)return cb?jsonp(cb,b):new Response(t,{status:hit.status,headers:headers(true,{'X-Kuda-Cache':'HIT'})})}}
 const target=new URL(GAS),params=normalizeTargetParams(incoming,action);params.forEach((v,k)=>target.searchParams.append(k,v));
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);
 try{const upstream=await fetch(target.toString(),{method:'GET',redirect:'follow',cache:'no-store',signal:controller.signal,headers:{Accept:'application/json, text/plain;q=0.9, */*;q=0.8'}});const body=parseUpstream(await upstream.text());if(!body){const e={success:false,message:'Server mengembalikan respons tidak valid.'};return cb?jsonp(cb,e):Response.json(e,{status:502,headers:headers(false)})}if(QUEUE_WRITE_ACTIONS.has(requestedAction)&&upstream.ok)await purgeQueueCache(request);const runtimeMs=Date.now()-started;if(isRead&&upstream.ok){const stored=Response.json(body,{status:200,headers:headers(true,{'X-Kuda-Cache':'MISS','X-Kuda-Upstream-Ms':String(runtimeMs)})});await cache.put(key,stored.clone())}const responseHeaders=headers(isRead&&upstream.ok,{'X-Kuda-Upstream-Ms':String(runtimeMs)});return cb?jsonp(cb,body):Response.json(body,{status:upstream.ok?200:502,headers:responseHeaders})}catch(error){const runtimeMs=Date.now()-started;const body={success:false,message:error&&error.name==='AbortError'?'Server timeout.':'Gagal menghubungi server.'};return cb?jsonp(cb,body):Response.json(body,{status:504,headers:headers(false,{'X-Kuda-Upstream-Ms':String(runtimeMs)})})}finally{clearTimeout(timer)}}
