var KUDA_AUTH_TOKEN_CACHE_SECONDS=21600;
var KUDA_USERS_SHEET='users';
var KUDA_ADMIN_KEY='290979';

function kudaUsersSheet_(){var ss=SpreadsheetApp.getActiveSpreadsheet(),s=ss.getSheetByName(KUDA_USERS_SHEET);if(!s){s=ss.insertSheet(KUDA_USERS_SHEET);s.getRange(1,1,1,7).setValues([['ID','Username','Password','Nama','Status','Dibuat','Login Terakhir']]);s.setFrozenRows(1);}return s;}
function kudaUser_(r){return{id:String(r[0]||''),username:String(r[1]||''),password:String(r[2]||''),name:String(r[3]||r[1]||''),status:String(r[4]||'aktif').toLowerCase(),createdAt:r[5]?new Date(r[5]).toISOString():'',lastLogin:r[6]?new Date(r[6]).toISOString():''};}
function kudaSafeUser_(u){return{id:u.id,username:u.username,name:u.name,status:u.status,createdAt:u.createdAt,lastLogin:u.lastLogin};}
function kudaActive_(u){return['aktif','active','1','true','yes','ya'].indexOf(String(u.status||'aktif').trim().toLowerCase())>=0;}
function kudaFindUser_(username){var s=kudaUsersSheet_(),last=s.getLastRow();if(last<2)return null;var rows=s.getRange(2,1,last-1,7).getValues(),n=String(username||'').trim().toLowerCase();for(var i=0;i<rows.length;i++){if(String(rows[i][1]||'').trim().toLowerCase()===n)return{row:i+2,user:kudaUser_(rows[i])};}return null;}
function kudaTokenKey_(t){return'kudajitu_member_'+String(t);}
function kudaTokenUser_(token){if(!token)return null;try{var raw=CacheService.getScriptCache().get(kudaTokenKey_(token));if(!raw)return null;var x=JSON.parse(raw),f=kudaFindUser_(x.username);return f&&kudaActive_(f.user)?f.user:null;}catch(e){return null;}}
function kudaAuthResponse_(cb,d){return respond_(cb,d);}
function kudaLogin_(p){var u=String(p.username||'').trim(),pw=String(p.password||'');if(!u||!pw)return{success:false,message:'Username dan password wajib diisi.'};var f=kudaFindUser_(u);if(!f||!kudaActive_(f.user)||String(f.user.password)!==pw)return{success:false,message:'Username atau password salah.'};var s=kudaUsersSheet_();s.getRange(f.row,7).setValue(new Date());var token=Utilities.getUuid().replace(/-/g,'')+Utilities.getUuid().replace(/-/g,'');var user=f.user;CacheService.getScriptCache().put(kudaTokenKey_(token),JSON.stringify({username:user.username,id:user.id,name:user.name}),KUDA_AUTH_TOKEN_CACHE_SECONDS);user.lastLogin=new Date().toISOString();return{success:true,token:token,user:kudaSafeUser_(user),expiresIn:KUDA_AUTH_TOKEN_CACHE_SECONDS};}
function kudaSession_(p){var u=kudaTokenUser_(String(p.token||''));return u?{success:true,user:kudaSafeUser_(u)}:{success:false,message:'LOGIN_REQUIRED'};}
function kudaLogout_(p){try{CacheService.getScriptCache().remove(kudaTokenKey_(String(p.token||'')));}catch(e){}return{success:true};}
function kudaRequire_(p){var u=kudaTokenUser_(String(p.token||''));if(!u)throw new Error('LOGIN_REQUIRED');return u;}
function kudaUsers_(p){if(String(p.adminKey||'')!==KUDA_ADMIN_KEY)throw new Error('Akses admin tidak valid');var s=kudaUsersSheet_(),last=s.getLastRow(),out=[];if(last>=2)s.getRange(2,1,last-1,7).getValues().forEach(function(r){if(r[1])out.push(kudaSafeUser_(kudaUser_(r)));});return{success:true,users:out};}
function kudaSaveUser_(p){if(String(p.adminKey||'')!==KUDA_ADMIN_KEY)throw new Error('Akses admin tidak valid');var s=kudaUsersSheet_(),id=String(p.id||'').trim(),username=String(p.username||'').trim(),password=String(p.password||''),name=String(p.name||username).trim(),status=String(p.status||'aktif').trim()||'aktif';if(!username||!name)return{success:false,message:'Username dan nama wajib diisi.'};var same=kudaFindUser_(username);if(same&&String(same.user.id)!==id)return{success:false,message:'Username sudah digunakan.'};var row=-1,last=s.getLastRow();if(id&&last>=2){var ids=s.getRange(2,1,last-1,1).getValues();for(var i=0;i<ids.length;i++)if(String(ids[i][0])===id){row=i+2;break;}}if(row<0){if(!password)return{success:false,message:'Password wajib diisi untuk user baru.'};id=id||'USR_'+Date.now();s.appendRow([id,username,password,name,status,new Date(),'']);}else{s.getRange(row,2,1,4).setValues([[username,password||s.getRange(row,3).getValue(),name,status]]);}var f=kudaFindUser_(username);return{success:true,message:row<0?'User berhasil ditambahkan.':'User berhasil diperbarui.',user:kudaSafeUser_(f.user)};}
function kudaDeleteUser_(p){if(String(p.adminKey||'')!==KUDA_ADMIN_KEY)throw new Error('Akses admin tidak valid');var id=String(p.id||''),s=kudaUsersSheet_(),last=s.getLastRow();if(last<2)return{success:false,message:'User tidak ditemukan.'};var rows=s.getRange(2,1,last-1,1).getValues(),row=-1;for(var i=0;i<rows.length;i++)if(String(rows[i][0])===id){row=i+2;break;}if(row<0)return{success:false,message:'User tidak ditemukan.'};s.deleteRow(row);return{success:true,message:'User berhasil dihapus.'};}
function kudaAuthGet_(e){var p=e&&e.parameter?e.parameter:{},cb=p.callback||p.prefix||'',a=String(p.action||'').toLowerCase();if(a==='login')return kudaAuthResponse_(cb,kudaLogin_(p));if(a==='session')return kudaAuthResponse_(cb,kudaSession_(p));if(a==='logout')return kudaAuthResponse_(cb,kudaLogout_(p));if(a==='users')return kudaAuthResponse_(cb,kudaUsers_(p));if(a==='saveuser')return kudaAuthResponse_(cb,kudaSaveUser_(p));if(a==='deleteuser')return kudaAuthResponse_(cb,kudaDeleteUser_(p));if(a==='add'||a==='addbatch'){var user=kudaRequire_(p);p.requester=user.name||user.username;if(a==='add'){return _kudaOriginalDoGet_(e);}var raw=[];try{raw=JSON.parse(p.items||'[]');}catch(x){throw new Error('Format batch tidak valid');}var out={success:true,action:'addBatch',count:0,added:0,existing:0,ids:[]};for(var i=0;i<raw.length;i+=3){var chunk=raw.slice(i,i+3);p.items=JSON.stringify(chunk);var q={};Object.keys(p).forEach(function(k){if(k!=='callback'&&k!=='prefix')q[k]=p[k];});var r=_kudaOriginalDoGet_({parameter:q});var data=JSON.parse(r.getContent());if(!data.success)throw new Error(data.message||'Batch gagal');out.count+=Number(data.count||0);out.added+=Number(data.added||0);out.existing+=Number(data.existing||0);out.ids=out.ids.concat(data.ids||[]);}return kudaAuthResponse_(cb,out);}return null;}
var _kudaOriginalDoGet_=doGet;
doGet=function(e){var p=e&&e.parameter?e.parameter:{},a=String(p.action||'').toLowerCase();if(['login','session','logout','users','saveuser','deleteuser','add','addbatch'].indexOf(a)>=0){try{return kudaAuthGet_(e);}catch(err){var cb=p.callback||p.prefix||'';return respond_(cb,{success:false,message:String(err.message||err),data:[]});}}return _kudaOriginalDoGet_(e);};
